x1 = int(input())
x2 = int(input())
x3 = int(input())
x4 = int(input())
x5 = int(input())
print("Наименьшее число =", min(x1, x2, x3, x4, x5))
print("Наибольшее число =", max(x1, x2, x3, x4, x5))